### ISSUE TITLE
reverserを動かす

### ISSUE THREAD

**Issue by pei0804** [pei0804/aws_gameday_2020_02_06#7]

**Comment by futuremaze** [comment]
以下のリクエストを飛ばすと400エラーが返却される
```shell
curl -H 'Content-Type:application/json' -H 'User-Agent:iPhone' -H 'Accept-Encoding:gzip,deflate' -d "{'RequestId': 'test', 'Message': 'ABCDE' }" http://54.184.90.193/                                       <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

**Comment by futuremaze** [comment]
以下で上手くいった。

```bash
curl -H 'Content-Type:application/json' -d '{"RequestId": "test", "Message": "ABCDE" }' http://54.184.90.193/
{"Message": "b43b0710f5824e6c9002bbbac0eb8b14EDCBA", "Signature": "XTqaNawNpeDyXy7OdpcErsfIlXpIjDk8vHY7sKtOygY="}%     
```

**Comment by pei0804** [comment]
make 作っといた
https://github.com/pei0804/aws_gameday_2020_02_06/blob/master/reverser/Makefile

**Comment by futuremaze** [comment]
![image](https://user-images.githubusercontent.com/2173404/73909989-5d6d8c00-48f1-11ea-8eb1-4de87f183088.png)

**Comment by futuremaze** [comment]
ECR リポジトリが削除されていた

**Comment by futuremaze** [comment]
再作成
![image](https://user-images.githubusercontent.com/2173404/73910147-cce37b80-48f1-11ea-92e9-1056d21c7a68.png)

**Comment by futuremaze** [comment]
753600854378.dkr.ecr.us-east-1.amazonaws.com/unicorn-service-reverser:latest

**Comment by futuremaze** [comment]
VPCのインターネット接続がNGだったため、イメージが取得できなかった。

**Comment by futuremaze** [comment]
ルートへのアクセスは200OK返る

% curl  http://34.217.33.132
{"Status": "OK"}%

**Comment by futuremaze** [comment]
![image](https://user-images.githubusercontent.com/2173404/73912487-f3a4b080-48f7-11ea-92cc-c52c4697cc81.png)
